#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: "3.6"

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  common: {}
  druid_shared: {}
  zookeeper_data: {}
  zookeeper_datalog: {}
  zoo_logs: {}

networks:
  infra_iot-big-data-infastructure_iot_bigdata:
    external: true

services:
  zookeeper1:
    image: zookeeper:latest
    hostname: zookeeper1
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - zoo_logs:/logs
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure

  postgres:
    image: postgres:latest
    volumes:
      - metadata_data:/druid/data/postgres
    environment:
       PGDATA: /druid/data/postgres
       POSTGRES_PASSWORD: va~;!2d4^&YLe;5#
       POSTGRES_USER: druid
       POSTGRES_DB: druid
    command: -p 5442
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure

  coordinator:
    image: apache/druid:0.22.0
    hostname: coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
      # - common:/opt/druid/conf/druid/cluster/_common
    command:
      - coordinator
    configs:
      - source: common_runtime_config
        target: /opt/druid/conf/druid/_common/common.runtime.properties
      - source: common_log4j_config
        target: /opt/druid/conf/druid/_common/log4j2.xml
      - source: coordinator_jvm_config
        target: /opt/druid/conf/druid/coordinator/jvm.config
      - source: coordinator_runtime_config
        target: /opt/druid/conf/druid/coordinator/runtime.properties
    # env_file:
    #   - environment
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure
       
  broker:
    image: apache/druid:0.22.0
    hostname: broker
    volumes:
      - broker_var:/opt/druid/var
      # - common:/opt/druid/conf/druid/cluster/_common
    command:
      - broker
    configs:
      - source: common_runtime_config
        target: /opt/druid/conf/druid/_common/common.runtime.properties
      - source: common_log4j_config
        target: /opt/druid/conf/druid/_common/log4j2.xml
      - source: broker_jvm_config
        target: /opt/druid/conf/druid/broker/jvm.config
      - source: broker_runtime_config
        target: /opt/druid/conf/druid/broker/runtime.properties
    # env_file:
    #   - broker_env
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure
      
  historical:
    image: apache/druid:0.22.0
    hostname: historical
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
      # - common:/opt/druid/conf/druid/cluster/_common
    command:
      - historical
    configs:
      - source: common_runtime_config
        target: /opt/druid/conf/druid/_common/common.runtime.properties
      - source: common_log4j_config
        target: /opt/druid/conf/druid/_common/log4j2.xml
      - source: historical_jvm_config
        target: /opt/druid/conf/druid/historical/jvm.config
      - source: historical_runtime_config
        target: /opt/druid/conf/druid/historical/runtime.properties
    # env_file:
    #   - historical_env
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure
      
  middlemanager:
    image: apache/druid:0.22.0
    hostname: middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
      # - common:/opt/druid/conf/druid/cluster/_common
    command:
      - middleManager
    configs:
      - source: common_runtime_config
        target: /opt/druid/conf/druid/_common/common.runtime.properties
      - source: common_log4j_config
        target: /opt/druid/conf/druid/_common/log4j2.xml
      - source: middleManager_jvm_config
        target: /opt/druid/conf/druid/middleManager/jvm.config
      - source: middleManager_runtime_config
        target: /opt/druid/conf/druid/middleManager/runtime.properties
    # env_file:
    #   - middlemanager_env
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure
      
  router:
    image: apache/druid:0.22.0
    hostname: router
    volumes:
      - router_var:/opt/druid/var
      # - common:/opt/druid/conf/druid/cluster/_common
    ports:
      - "8888:8888"
    command:
      - router
    configs:
      - source: common_runtime_config
        target: /opt/druid/conf/druid/_common/common.runtime.properties
      - source: common_log4j_config
        target: /opt/druid/conf/druid/_common/log4j2.xml
      - source: router_jvm_config
        target: /opt/druid/conf/druid/router/jvm.config
      - source: router_runtime_config
        target: /opt/druid/conf/druid/router/runtime.properties
    # env_file:
    #   - router_env
    networks:
      - infra_iot-big-data-infastructure_iot_bigdata
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure

configs:
  common_runtime_config:
    file: ./conf/druid/_common/common.runtime.properties
  common_log4j_config:
    file: ./conf/druid/_common/log4j2.xml
  broker_jvm_config:
    file: ./conf/druid/broker/jvm.config
  broker_runtime_config:
    file: ./conf/druid/broker/runtime.properties
  router_jvm_config:
    file: ./conf/druid/router/jvm.config
  router_runtime_config:
    file: ./conf/druid/router/runtime.properties
  coordinator_jvm_config:
    file: ./conf/druid/coordinator/jvm.config
  coordinator_runtime_config:
    file: ./conf/druid/coordinator/runtime.properties
  historical_jvm_config:
    file: ./conf/druid/historical/jvm.config
  historical_runtime_config:
    file: ./conf/druid/historical/runtime.properties
  middleManager_jvm_config:
    file: ./conf/druid/middleManager/jvm.config
  middleManager_runtime_config:
    file: ./conf/druid/middleManager/runtime.properties
  overlord_jvm_config:
    file: ./conf/druid/overlord/jvm.config
  overlord_runtime_config:
    file: ./conf/druid/overlord/runtime.properties