version: "3.6"

volumes:
  zookeeper_data: {}
  zookeeper_datalog: {}

networks:
  zoo_net:
    attachable: true

services:
  zookeeper1:
    image: zookeeper:latest
    hostname: zookeeper1
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - zoo_net
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
    deploy:                 
      replicas: 1                 
      placement:                                                                                         
        constraints: [node.hostname == server3.ianic.gr]                                                                                      
      restart_policy:                                
        condition: on-failure